# -*- coding: utf-8 -*-
"""Banknote.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O12mCp6Dr5fgTA7LkRgkpNNcPT2zMJsd
"""

# -*- coding: utf-8 -*-
"""banknoteactivity.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16TDXVFqdxFl14zkiHtBAdPi-AGrsDQX8
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline
from sklearn.model_selection import train_test_split
import warnings 
warnings.filterwarnings('ignore')
from sklearn.ensemble import RandomForestClassifier

from google.colab import drive
drive.mount('/content/drive')

data=pd.read_csv('/content/drive/MyDrive/docker_activity/BankNote_Authentication (1).csv')

data

data.dtypes

data.isna().sum()

data.describe()

plt.figure(figsize=(4,4))
sns.heatmap(data.corr(),annot=True,cmap='Blues',cbar=True)

cat_cols=data.select_dtypes('int64').columns
cat_cols

cat_cols=cat_cols.astype('category')

num_cols=data[['variance','skewness','curtosis']]

X=data.drop('class',axis=1)
y=data['class']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=123,stratify=y)

from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score

Banknote= RandomForestClassifier()

Banknote.fit(X_train,y_train)
predict=Banknote.predict(X_test)
score=accuracy_score(y_test,predict)

score

import pickle
pickle_out = open("Banknote.pkl","wb")
pickle.dump(Banknote, pickle_out)
pickle_out.close()